### ISSUE TITLE
Doesn't apply or compile with wine 2.22

### ISSUE THREAD

**Issue by josch** [00cpxxx/wine-xinput#8]
Hi,

your patch doesn't apply anymore since `dlls/xinput1_3/xinput1_3_main.c` was renamed to `dlls/xinput1_3/xinput_main.c` in commit ff8c49ee. But even after fixing the patch accordingly, wine fails to build with the following error:

```
make[2]: Entering directory '/<<PKGBUILDDIR>>/dlls/xinput1_1'
gcc -m64 -c -o xinput_main.o ../xinput1_3/xinput_main.c -I. -I../xinput1_3 -I../../include -D__WINESRC__ \
  -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -gdwarf-2 \
  -gstrict-dwarf -Werror -Wdate-time -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wno-error
../../tools/wrc/wrc -o version.res -m64 --nostdinc -I. -I../xinput1_3 -I../../include -D__WINESRC__ \
  version.rc
../../tools/winegcc/winegcc -o xinput1_1.dll.so -B../../tools/winebuild -m64 -fasynchronous-unwind-tables -shared xinput1_1.spec \
  xinput_main.o version.res ../../libs/port/libwine_port.a -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/usr/lib/x86_64-linux-gnu/wine-development
xinput_main.o: In function `dinput_acquire':
./dlls/xinput1_1/../xinput1_3/xinput_main.c:217: undefined reference to `c_dfDIJoystick2'
xinput_main.o: In function `dinput_start':
./dlls/xinput1_1/../xinput1_3/xinput_main.c:351: undefined reference to `IID_IDirectInput8A'
/usr/bin/ld: xinput_main.o: relocation R_X86_64_PC32 against undefined hidden symbol `IID_IDirectInput8A' can not be used when making a shared object
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
winegcc: gcc failed
Makefile:209: recipe for target 'xinput1_1.dll.so' failed
make[2]: *** [xinput1_1.dll.so] Error 2
make[2]: Leaving directory '/<<PKGBUILDDIR>>/dlls/xinput1_1'
Makefile:18042: recipe for target 'dlls/xinput1_1' failed
make[1]: *** [dlls/xinput1_1] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
```

Besides rebasing your patch to the recent wine version, could you write down (probably in the README) against which wine version you last rebased your patch and had it known working? It seems to compile fine with 2.0.3 but I have yet to test if it works.

**Comment by josch** [comment]
It works fine with wine 2.0.3. You can also add "Tower 57" to the list of games that works with your patch.

**Comment by 00cpxxx** [comment]
Thanks, I'll take a look at some point in December. The changes that broke it were made between 2.17 and 2.18. So the last working development version is 2.17.
